version: "3.9"

services:
  # Backend Service (Spring Boot)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/disc_platform
      - SPRING_DATASOURCE_USERNAME=disc_platform
      - SPRING_DATASOURCE_PASSWORD=disc_platform
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_URL=https://api.openai.com/v1
      - OPENAI_API_MODEL=gpt-3.5-turbo
      - OPENAI_API_TEMPERATURE=0.5
    depends_on:
      - redis
      - db
    networks:
      - app-network

  # Frontend Service (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=disc_platform
      - POSTGRES_USER=disc_platform
      - POSTGRES_PASSWORD=disc_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Redis for caching
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
