services:
  # Backend Service (Spring Boot)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/disc_analysis
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      # 🔹 OpenAI configuration
      - OPENAI_API_KEY=your_open_ai_api_key
      - OPENAI_API_URL=https://api.openai.com/v1
      - OPENAI_API_MODEL=gpt-3.5-turbo
      - OPENAI_API_TEMPERATURE=0.5
    depends_on:
      - redis
      - db
    networks:
      - app-network

  # Frontend Service (React)
  frontend:
    build:
      context: ./frontend  # шлях до вашої фронтенд директорії
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=disc_analysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Redis for caching
  redis:
    image: redis:7.2
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
